//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mVanArea
    {
        public int VanAreaId { get; set; }
        public string VanAreaName { get; set; }
        public Nullable<System.DateTime> Creationdate { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<int> Userid { get; set; }
    }
}
